import type { Property, Category, Testimonial, FAQ, CarouselSlide, Blog, Inquiry } from '@/types/database'

// ============================================================
// DEMO PROPERTIES
// ============================================================

export const demoProperties: Property[] = [
  {
    id: '1',
    property_id: 'PA-2024-001',
    title: 'Luxurious 3 BHK Apartment in Baner',
    slug: 'luxurious-3bhk-apartment-baner',
    description: 'Experience luxury living in this stunning 3 BHK apartment located in the heart of Baner, Jalgaon. This premium residence features modern architecture, high-quality finishes, and breathtaking views. The apartment comes with a modular kitchen, imported marble flooring, and designer bathroom fittings. Enjoy world-class amenities including a swimming pool, gym, clubhouse, and landscaped gardens.',
    highlights: ['Italian marble flooring', 'Modular kitchen with chimney', 'Large balcony with city view', 'Premium bathroom fittings', 'Smart home features', 'Covered parking for 2 cars'],
    property_type: 'apartment',
    status: 'for_sale',
    construction_status: 'ready_to_move',
    price: 12500000,
    price_label: '₹1.25 Cr',
    price_negotiable: true,
    area_sqft: 1450,
    bedrooms: 3,
    bathrooms: 2,
    balcony: 2,
    parking: 2,
    floor: 12,
    total_floors: 24,
    facing: 'East',
    ownership: 'Freehold',
    address: 'Baner Road, Near Balewadi High Street',
    location: 'Baner, Jalgaon',
    city: 'Jalgaon',
    state: 'Maharashtra',
    pincode: '411045',
    thumbnail_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop',
    is_featured: true,
    is_active: true,
    is_draft: false,
    views: 342,
    inquiry_count: 28,
    seo_title: 'Luxurious 3 BHK Apartment for Sale in Baner, Jalgaon | PrimeAxis',
    seo_description: 'Premium 3 BHK apartment in Baner with world-class amenities. 1450 sq.ft, ready to move, ₹1.25 Cr. Contact PrimeAxis for site visit.',
    created_at: '2024-06-15T10:00:00Z',
    updated_at: '2024-06-20T14:30:00Z',
    images: [
      { id: '1', property_id: '1', url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop', caption: 'Living Room', display_order: 0, is_thumbnail: true, created_at: '' },
      { id: '2', property_id: '1', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop', caption: 'Master Bedroom', display_order: 1, is_thumbnail: false, created_at: '' },
      { id: '3', property_id: '1', url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=800&fit=crop', caption: 'Kitchen', display_order: 2, is_thumbnail: false, created_at: '' },
      { id: '4', property_id: '1', url: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=1200&h=800&fit=crop', caption: 'Bathroom', display_order: 3, is_thumbnail: false, created_at: '' },
    ],
  },
  {
    id: '2',
    property_id: 'PA-2024-002',
    title: 'Premium 4 BHK Villa in Koregaon Park',
    slug: 'premium-4bhk-villa-koregaon-park',
    description: 'A magnificent 4 BHK villa in the prestigious Koregaon Park area. This villa offers an unmatched blend of luxury and comfort with a private garden, swimming pool, and modern interiors. Perfect for families seeking a premium lifestyle.',
    highlights: ['Private swimming pool', 'Landscaped garden with deck', 'Home theatre room', 'Italian kitchen', 'Servant quarters', 'Triple car garage'],
    property_type: 'luxury_villa',
    status: 'for_sale',
    construction_status: 'ready_to_move',
    price: 45000000,
    price_label: '₹4.5 Cr',
    price_negotiable: false,
    area_sqft: 3500,
    bedrooms: 4,
    bathrooms: 4,
    balcony: 3,
    parking: 3,
    floor: 0,
    total_floors: 2,
    facing: 'North',
    ownership: 'Freehold',
    address: 'Lane 7, Koregaon Park',
    location: 'Koregaon Park, Jalgaon',
    city: 'Jalgaon',
    state: 'Maharashtra',
    pincode: '411001',
    thumbnail_url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop',
    is_featured: true,
    is_active: true,
    is_draft: false,
    views: 567,
    inquiry_count: 45,
    created_at: '2024-06-10T10:00:00Z',
    updated_at: '2024-06-18T14:30:00Z',
    images: [
      { id: '5', property_id: '2', url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop', caption: 'Exterior', display_order: 0, is_thumbnail: true, created_at: '' },
      { id: '6', property_id: '2', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop', caption: 'Garden View', display_order: 1, is_thumbnail: false, created_at: '' },
    ],
  },
  {
    id: '3',
    property_id: 'PA-2024-003',
    title: 'Modern 2 BHK Flat in Hinjewadi Phase 1',
    slug: 'modern-2bhk-flat-hinjewadi',
    description: 'A well-designed 2 BHK apartment in the IT hub of Hinjewadi. Close to top IT companies, shopping malls, and entertainment hubs. Ideal for working professionals.',
    highlights: ['Close to IT Park', 'Modular kitchen', 'Covered parking', 'Children play area', 'Security with CCTV'],
    property_type: 'apartment',
    status: 'for_sale',
    construction_status: 'ready_to_move',
    price: 6500000,
    price_label: '₹65 Lakh',
    price_negotiable: true,
    area_sqft: 950,
    bedrooms: 2,
    bathrooms: 2,
    balcony: 1,
    parking: 1,
    floor: 8,
    total_floors: 18,
    facing: 'West',
    ownership: 'Freehold',
    address: 'Hinjewadi Phase 1, Near Rajiv Gandhi IT Park',
    location: 'Hinjewadi, Jalgaon',
    city: 'Jalgaon',
    state: 'Maharashtra',
    pincode: '411057',
    thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
    is_featured: false,
    is_active: true,
    is_draft: false,
    views: 189,
    inquiry_count: 15,
    created_at: '2024-06-12T10:00:00Z',
    updated_at: '2024-06-15T14:30:00Z',
    images: [
      { id: '7', property_id: '3', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop', caption: 'Living Room', display_order: 0, is_thumbnail: true, created_at: '' },
    ],
  },
  {
    id: '4',
    property_id: 'PA-2024-004',
    title: 'Commercial Office Space in Viman Nagar',
    slug: 'commercial-office-viman-nagar',
    description: 'Premium commercial office space in the heart of Viman Nagar. Fully furnished with modern amenities, perfect for IT companies and startups. Excellent connectivity and parking facilities.',
    highlights: ['Fully furnished', 'Central AC', 'Conference room', 'Pantry area', 'High-speed internet ready', '24/7 access'],
    property_type: 'office_space',
    status: 'for_rent',
    construction_status: 'ready_to_move',
    price: 85000,
    price_label: '₹85,000/month',
    price_negotiable: true,
    area_sqft: 1200,
    bedrooms: 0,
    bathrooms: 2,
    balcony: 0,
    parking: 4,
    floor: 3,
    total_floors: 8,
    facing: 'South',
    ownership: 'Leasehold',
    address: 'Phoenix Market City Road, Viman Nagar',
    location: 'Viman Nagar, Jalgaon',
    city: 'Jalgaon',
    state: 'Maharashtra',
    pincode: '411014',
    thumbnail_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop',
    is_featured: true,
    is_active: true,
    is_draft: false,
    views: 234,
    inquiry_count: 19,
    created_at: '2024-06-08T10:00:00Z',
    updated_at: '2024-06-14T14:30:00Z',
    images: [
      { id: '8', property_id: '4', url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop', caption: 'Office Interior', display_order: 0, is_thumbnail: true, created_at: '' },
    ],
  },
  {
    id: '5',
    property_id: 'PA-2024-005',
    title: 'Beautiful Farm House near Jalgaon-Mumbai Expressway',
    slug: 'beautiful-farmhouse-jalgaon-mumbai-expressway',
    description: 'Escape to this beautiful farmhouse set amidst lush green surroundings near the Jalgaon-Mumbai Expressway. Spread across 1 acre, this property offers complete tranquility with modern amenities.',
    highlights: ['1 acre land', 'Fruit orchard', 'Private bore well', 'Gazebo & sit-out area', 'Caretaker cottage', 'Boundary wall with gate'],
    property_type: 'farmhouse',
    status: 'for_sale',
    construction_status: 'ready_to_move',
    price: 25000000,
    price_label: '₹2.5 Cr',
    price_negotiable: true,
    area_sqft: 43560,
    bedrooms: 3,
    bathrooms: 3,
    balcony: 2,
    parking: 5,
    facing: 'North-East',
    ownership: 'Freehold',
    address: 'Near Lonavala, Jalgaon-Mumbai Expressway',
    location: 'Lonavala, Jalgaon',
    city: 'Jalgaon',
    state: 'Maharashtra',
    thumbnail_url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
    is_featured: true,
    is_active: true,
    is_draft: false,
    views: 445,
    inquiry_count: 32,
    created_at: '2024-06-05T10:00:00Z',
    updated_at: '2024-06-12T14:30:00Z',
    images: [
      { id: '9', property_id: '5', url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&h=800&fit=crop', caption: 'Front View', display_order: 0, is_thumbnail: true, created_at: '' },
    ],
  },
  {
    id: '6',
    property_id: 'PA-2024-006',
    title: 'Residential Plot in Wakad',
    slug: 'residential-plot-wakad',
    description: 'Prime residential plot in the rapidly developing area of Wakad. Clear title, NA sanctioned, ready for construction. Close to schools, hospitals, and IT parks.',
    highlights: ['NA sanctioned', 'Clear title', 'All amenities nearby', 'Road facing', 'Corner plot', 'Ready for construction'],
    property_type: 'plot',
    status: 'for_sale',
    construction_status: 'ready_to_move',
    price: 9000000,
    price_label: '₹90 Lakh',
    price_negotiable: true,
    area_sqft: 2400,
    bedrooms: 0,
    bathrooms: 0,
    facing: 'East',
    ownership: 'Freehold',
    address: 'Wakad, Near Datta Mandir Chowk',
    location: 'Wakad, Jalgaon',
    city: 'Jalgaon',
    state: 'Maharashtra',
    pincode: '411057',
    thumbnail_url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop',
    is_featured: false,
    is_active: true,
    is_draft: false,
    views: 156,
    inquiry_count: 11,
    created_at: '2024-06-02T10:00:00Z',
    updated_at: '2024-06-10T14:30:00Z',
    images: [
      { id: '10', property_id: '6', url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=800&fit=crop', caption: 'Plot View', display_order: 0, is_thumbnail: true, created_at: '' },
    ],
  },
]

// ============================================================
// DEMO CATEGORIES
// ============================================================

export const demoCategories: Category[] = [
  { id: '1', name: 'Residential', slug: 'residential', icon: 'home', description: 'Find your dream home', display_order: 1, is_active: true, created_at: '', property_count: 45 },
  { id: '2', name: 'Commercial', slug: 'commercial', icon: 'building-2', description: 'Office & retail spaces', display_order: 2, is_active: true, created_at: '', property_count: 22 },
  { id: '3', name: 'Plots', slug: 'plots', icon: 'map', description: 'Invest in prime land', display_order: 3, is_active: true, created_at: '', property_count: 18 },
  { id: '4', name: 'Farm House', slug: 'farmhouse', icon: 'tree-pine', description: 'Rural luxury living', display_order: 4, is_active: true, created_at: '', property_count: 8 },
  { id: '5', name: 'Rental', slug: 'rental', icon: 'key', description: 'Ready to move rentals', display_order: 5, is_active: true, created_at: '', property_count: 35 },
  { id: '6', name: 'Luxury Villas', slug: 'luxury-villas', icon: 'crown', description: 'Premium villas', display_order: 6, is_active: true, created_at: '', property_count: 12 },
  { id: '7', name: 'Apartments', slug: 'apartments', icon: 'building', description: 'Modern apartments', display_order: 7, is_active: true, created_at: '', property_count: 67 },
  { id: '8', name: 'Independent House', slug: 'independent-house', icon: 'house', description: 'Standalone bungalows', display_order: 8, is_active: true, created_at: '', property_count: 15 },
  { id: '9', name: 'Office Space', slug: 'office-space', icon: 'briefcase', description: 'Work ready offices', display_order: 9, is_active: true, created_at: '', property_count: 28 },
  { id: '10', name: 'Warehouse', slug: 'warehouse', icon: 'package', description: 'Storage & logistics', display_order: 10, is_active: true, created_at: '', property_count: 9 },
]

// ============================================================
// DEMO TESTIMONIALS
// ============================================================

export const demoTestimonials: Testimonial[] = [
  { id: '1', customer_name: 'Rajesh Sharma', rating: 5, review: 'PrimeAxis made our dream of owning a home in Jalgaon a reality. Their team was professional, transparent, and guided us through every step. We found our perfect 3BHK in Baner within 3 weeks!', property_type: 'Apartment', location: 'Baner, Jalgaon', display_order: 1, is_active: true, created_at: '2024-05-01' },
  { id: '2', customer_name: 'Priya Mehta', rating: 5, review: 'Excellent service from start to finish. The agents are knowledgeable and never pushed us into any decisions. The loan assistance they provided saved us significant time and effort.', property_type: 'Independent House', location: 'Kothrud, Jalgaon', display_order: 2, is_active: true, created_at: '2024-04-15' },
  { id: '3', customer_name: 'Vikram Patel', rating: 4, review: 'Very professional team. They showed us properties that truly matched our budget and requirements. The legal assistance was a huge help. Highly recommend PrimeAxis.', property_type: 'Commercial', location: 'Hinjewadi, Jalgaon', display_order: 3, is_active: true, created_at: '2024-04-01' },
  { id: '4', customer_name: 'Anita Desai', rating: 5, review: 'I was skeptical about buying property remotely, but PrimeAxis made it seamless. Regular updates, video tours, and thorough documentation support. Truly a premium experience!', property_type: 'Luxury Villa', location: 'Kalyani Nagar, Jalgaon', display_order: 4, is_active: true, created_at: '2024-03-20' },
  { id: '5', customer_name: 'Suresh Kumar', rating: 5, review: 'Found our dream farmhouse through PrimeAxis. The team understood exactly what we wanted and presented us with options that exceeded our expectations.', property_type: 'Farm House', location: 'Jalgaon Outskirts', display_order: 5, is_active: true, created_at: '2024-03-10' },
  { id: '6', customer_name: 'Neha Singh', rating: 4, review: 'Great experience overall. PrimeAxis has a vast network of verified properties. Their after-sales support continues even after the deal is closed. Very trustworthy brokerage.', property_type: 'Apartment', location: 'Viman Nagar, Jalgaon', display_order: 6, is_active: true, created_at: '2024-02-28' },
]

// ============================================================
// DEMO FAQs
// ============================================================

export const demoFAQs: FAQ[] = [
  { id: '1', question: 'How do I schedule a property visit?', answer: 'You can schedule a property visit by clicking the "Schedule Visit" button on any property page, or by contacting us directly via WhatsApp or phone. Our team will confirm your appointment within 2 hours.', category: 'general', display_order: 1, is_active: true, created_at: '' },
  { id: '2', question: 'Is PrimeAxis a verified real estate brokerage?', answer: 'Yes, PrimeAxis is a registered and verified real estate brokerage with years of experience in the Jalgaon property market. All our listings are verified and our team of experts guides you through every step.', category: 'general', display_order: 2, is_active: true, created_at: '' },
  { id: '3', question: 'Do you assist with home loans?', answer: 'Absolutely! We have tie-ups with leading banks and NBFCs to help you get the best home loan rates. Our loan assistance experts will help you with documentation, eligibility, and loan processing at no extra cost.', category: 'finance', display_order: 3, is_active: true, created_at: '' },
  { id: '4', question: 'What is the process to buy a property through PrimeAxis?', answer: 'Our 4-step process: 1) Browse & shortlist properties, 2) Schedule a site visit, 3) Finalize the property with expert negotiation, 4) Complete documentation & registration. We assist at every step.', category: 'buying', display_order: 4, is_active: true, created_at: '' },
  { id: '5', question: 'Do you charge any brokerage fee?', answer: 'Our brokerage fees are competitive and transparent. We charge a standard 1-2% brokerage on successful transactions. For rental properties, it is typically equivalent to one month\'s rent. All fees are discussed upfront.', category: 'finance', display_order: 5, is_active: true, created_at: '' },
  { id: '6', question: 'Can I list my property for sale or rent?', answer: 'Yes! Property owners can list their properties with us for free. We provide professional photography, marketing, and buyer/tenant screening services. Contact us to get started.', category: 'selling', display_order: 6, is_active: true, created_at: '' },
  { id: '7', question: 'What documents are needed to buy a property?', answer: 'Generally required: Aadhar Card, PAN Card, Bank statements (6 months), Salary slips (3 months), Form 16, and property documents. Our legal team will provide a complete checklist based on your specific case.', category: 'legal', display_order: 7, is_active: true, created_at: '' },
  { id: '8', question: 'Do you provide legal assistance?', answer: 'Yes, we provide complete legal assistance including title verification, sale deed drafting, registration, and mutation. We partner with experienced property lawyers to ensure a smooth and secure transaction.', category: 'legal', display_order: 8, is_active: true, created_at: '' },
]

// ============================================================
// DEMO CAROUSEL SLIDES
// ============================================================

export const demoCarouselSlides: CarouselSlide[] = [
  { id: '1', title: 'Find Your Dream Property in Jalgaon', subtitle: 'Verified listings, expert guidance, and the best deals across residential and commercial properties', slide_type: 'image', media_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1920&h=1080&fit=crop', button_text: 'View Properties', button_url: '/properties', display_order: 1, is_active: true, created_at: '', updated_at: '' },
  { id: '2', title: 'Luxury Living Redefined', subtitle: 'Explore our exclusive collection of premium villas, penthouses and luxury apartments', slide_type: 'image', media_url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1920&h=1080&fit=crop', button_text: 'Explore Luxury', button_url: '/properties?type=luxury_villa', display_order: 2, is_active: true, created_at: '', updated_at: '' },
  { id: '3', title: 'Smart Investment, Better Future', subtitle: 'Discover high-yield commercial properties and prime plots in growth corridors', slide_type: 'image', media_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1920&h=1080&fit=crop', button_text: 'Invest Now', button_url: '/properties?type=commercial', display_order: 3, is_active: true, created_at: '', updated_at: '' },
]

// ============================================================
// DEMO BLOGS
// ============================================================

export const demoBlogs: Blog[] = [
  {
    id: '1',
    title: 'Top 10 Emerging Localities in Jalgaon for Real Estate Investment in 2024',
    slug: 'top-10-emerging-localities-jalgaon-2024',
    excerpt: 'Discover the best localities in Jalgaon for property investment in 2024. From Hinjewadi to Kharadi, explore areas with highest growth potential.',
    featured_image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=500&fit=crop',
    status: 'published',
    tags: ['Investment', 'Jalgaon', 'Real Estate'],
    views: 1245,
    published_at: '2024-06-01T10:00:00Z',
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    content: '<h2>Why Jalgaon is the Best City for Real Estate Investment</h2><p>Jalgaon has emerged as one of India\'s top cities for real estate investment...</p>',
  },
  {
    id: '2',
    title: 'Complete Guide to Home Loan Process in India 2024',
    slug: 'complete-guide-home-loan-process-india-2024',
    excerpt: 'Everything you need to know about getting a home loan in India. From eligibility to documentation, interest rates, and tips to get the best deal.',
    featured_image: 'https://images.unsplash.com/photo-1560472355-536de3962603?w=800&h=500&fit=crop',
    status: 'published',
    tags: ['Home Loan', 'Finance', 'Guide'],
    views: 892,
    published_at: '2024-05-20T10:00:00Z',
    created_at: '2024-05-20T10:00:00Z',
    updated_at: '2024-05-20T10:00:00Z',
    content: '<h2>Understanding Home Loans</h2><p>A home loan is a financial product offered by banks...</p>',
  },
  {
    id: '3',
    title: 'RERA: How It Protects Home Buyers in Maharashtra',
    slug: 'rera-protects-home-buyers-maharashtra',
    excerpt: 'Learn how RERA (Real Estate Regulatory Authority) protects your rights as a home buyer in Maharashtra and what you should know before buying.',
    featured_image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=500&fit=crop',
    status: 'published',
    tags: ['RERA', 'Legal', 'Home Buying'],
    views: 634,
    published_at: '2024-05-10T10:00:00Z',
    created_at: '2024-05-10T10:00:00Z',
    updated_at: '2024-05-10T10:00:00Z',
    content: '<h2>What is RERA?</h2><p>RERA stands for Real Estate Regulatory Authority...</p>',
  },
]

// ============================================================
// DEMO INQUIRIES (for admin dashboard)
// ============================================================

export const demoInquiries: Inquiry[] = [
  { id: '1', customer_name: 'Amit Sharma', customer_phone: '+919876543210', customer_email: 'amit@example.com', message: 'Interested in the 3BHK apartment in Baner', property_id: '1', property_title: 'Luxurious 3 BHK Apartment in Baner', source: 'website_form', status: 'new', created_at: '2024-06-20T10:00:00Z', updated_at: '2024-06-20T10:00:00Z' },
  { id: '2', customer_name: 'Sneha Patel', customer_phone: '+919876543211', message: 'Want to visit the villa in Koregaon Park', property_id: '2', property_title: 'Premium 4 BHK Villa in Koregaon Park', source: 'whatsapp', status: 'contacted', created_at: '2024-06-19T10:00:00Z', updated_at: '2024-06-19T14:00:00Z' },
  { id: '3', customer_name: 'Rahul Desai', customer_phone: '+919876543212', customer_email: 'rahul@example.com', message: 'Looking for office space, need details', property_id: '4', property_title: 'Commercial Office Space in Viman Nagar', source: 'call', status: 'site_visit', created_at: '2024-06-18T10:00:00Z', updated_at: '2024-06-19T10:00:00Z' },
  { id: '4', customer_name: 'Pooja Singh', customer_phone: '+919876543213', message: 'Farmhouse inquiry - budget 3Cr', property_id: '5', property_title: 'Beautiful Farm House near Jalgaon-Mumbai Expressway', source: 'website_form', status: 'negotiation', created_at: '2024-06-17T10:00:00Z', updated_at: '2024-06-20T10:00:00Z' },
  { id: '5', customer_name: 'Karan Mehta', customer_phone: '+919876543214', message: 'Need 2BHK near Hinjewadi IT Park', source: 'whatsapp', status: 'interested', created_at: '2024-06-16T10:00:00Z', updated_at: '2024-06-18T10:00:00Z' },
]
